# This formula is auto-generated by GoReleaser on release.
# This template is here for reference / manual tap setup.
class Mcpguard < Formula
  desc "MCP configuration security scanner — protect your AI tooling"
  homepage "https://github.com/withaxiom/mcpguard"
  license "MIT"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/withaxiom/mcpguard/releases/download/v0.1.0/mcpguard_0.1.0_darwin_arm64.tar.gz"
      # sha256 will be filled by GoReleaser
    end
    on_intel do
      url "https://github.com/withaxiom/mcpguard/releases/download/v0.1.0/mcpguard_0.1.0_darwin_amd64.tar.gz"
      # sha256 will be filled by GoReleaser
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/withaxiom/mcpguard/releases/download/v0.1.0/mcpguard_0.1.0_linux_arm64.tar.gz"
      # sha256 will be filled by GoReleaser
    end
    on_intel do
      url "https://github.com/withaxiom/mcpguard/releases/download/v0.1.0/mcpguard_0.1.0_linux_amd64.tar.gz"
      # sha256 will be filled by GoReleaser
    end
  end

  def install
    bin.install "mcpguard"
  end

  test do
    system "#{bin}/mcpguard", "version"
  end
end
